# Generated by Django 3.2.20 on 2023-09-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
