# Generated by Django 3.2.20 on 2023-09-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_profile',
        ),
    ]
