# Generated by Django 3.2.20 on 2023-08-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_review_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
