# Generated by Django 3.2.20 on 2023-09-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_delivery_chargable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='delivery_chargable',
            new_name='delivery_charge',
        ),
    ]
