# Generated by Django 3.2.20 on 2023-09-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_delivery_chargable_product_delivery_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
